config/routes.rb
Rails.application.routes.draw do
  # resources :users
  
  devise_for :users, skip: [:registrations]
  root 'users#index'
  
  authenticate :user do
    resources :records, except: [:index]
    get 'datos-de-registro' => 'records#search' ,as: :data_list
    post 'traer-records' => 'records#data_list', as: :get_records
    resources :bus_routes do
      collection { post :import }
    end
    get '/programacion' => 'buses#index' ,as: :programacion
    resources :buses, except: [:index] do
      collection { post :import }
    end
    get '/autobuses' => 'buses#list_buses'

  end
  post '/checkpoint' => 'users#checkpoint' ,as: :user_checkpoint
  get '/usuarios' => 'users#list_users'
  scope "/coonatra" do
    resources :users, except: [:index,:show]
    resources :users, only: [] do
      collection do
        get ':id/autobuses' => 'users#bus_list' ,as: :bus_list
        post 'autobuses' => 'buses#bus_assignment' ,as: :bus_assignment
      end
    end

  end
end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id                     :integer          not null, primary key
#  username               :string           default(""), not null
#  role                   :integer
#  created_at             :datetime         not null
#  updated_at             :datetime         not null
#  email                  :string           default(""), not null
#  encrypted_password     :string           default(""), not null
#  reset_password_token   :string
#  reset_password_sent_at :datetime
#  remember_created_at    :datetime
#  sign_in_count          :integer          default(0), not null
#  current_sign_in_at     :datetime
#  last_sign_in_at        :datetime
#  current_sign_in_ip     :inet
#  last_sign_in_ip        :inet
#

class User < ActiveRecord::Base
  # role: goes from top prority to less priority
  # It's better to write it as a hash because you can have the numbers
  #   guiding the roles
  enum role: {
           Gerente: 0,
           Admin: 1,
           Lector: 2,
           Editor: 3
       }
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  validates :username, presence: true, uniqueness: true
  validates :role, presence: true
  # before_save :granted_permissions
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :buses

  # The method checks if the user that is creating new users is at least 'Admin'


  def self.all_by_role(current_user)
    if current_user.Gerente?
      return self.all
    elsif current_user.Admin?
      return self.where('role != ? AND role != ?', User.roles['Admin'],User.roles['Gerente'])
    else
      self.errors.add(:base, 'Admin Tiene que ser almenos administrador para consultar usuarios')
      return false
    end
  end
  private
  # Before the save action is trigger check if the 'current_user' has 'Gerente' or 'Admin' Role
  def granted_permissions
    if self.role != 'Gerente' && self.role != 'Admin'
      self.errors.add(:base, 'Admin Tiene que ser almenos administrador para poder guardar usuarios')
        false
    end
  end

end

app/controllers/users_controller.rb
require 'authorize_creation'
class UsersController < ApplicationController
	before_action :role_editor, if: :signed_in?, except: [:index, :checkpoint]
	before_action :role_reader, if: :signed_in?, except: [:index]
	before_action :authenticate_user!, except: [:index]
	before_action :modify_user, only: [:edit,:destroy,:update]

	def index
		unless user_signed_in?
			render "index"
		else
			case current_user.role
				when "Admin" , "Gerente"
					render "dashboard"
				when "Editor"
					if cookies[:checkpoint]
						redirect_to controller: "records", action: "new"
					else
						render :checkpoint
					end
				when "Lector"
					redirect_to controller: "records", action: "search"
				else
					puts"~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~"
					puts"case not go into"
			end
		end
	end

	def new
		@user = User.new
	end

	def create
		@user = User.new(user_params)
		autorize_user = AutorizeCreation.new(current_user)

		if autorize_user.admin_save(@user)
			puts "se ha creado el usuario #{@user.username} con id: #{@user.id}"
			flash[:notice] = "Se a creado el nuevo usuario #{@user.username}"
			redirect_to action: "list_users"
		else
			flash[:alert] = "El usuario #{@user.username} no pudo ser creado, revise su conexión"
			render "new"
		end
	end

	def edit
	end

	def update
		@user.attributes = user_params
		autorize_user = AutorizeCreation.new(current_user)
		if autorize_user.admin_save(@user)
			flash[:notice] = "Se ah actualizado el usuario #{@user.username}"
			redirect_to action: "list_users"
		else
			flash[:alert] = "El usuario #{@user.username} no pudo ser actualizado, revise su conexión"
			render "new"
		end
	end

	def destroy
		@user.destroy
	end

	def list_users
		@users = User.all_by_role(current_user)
	end

	def checkpoint
		cookies.permanent[:checkpoint] = checkpoint_params[:checkpoint]
		redirect_to controller: "records", action: "new"
	end

	def bus_list
		@user = User.find(params[:id])
		@buses = Bus.where('user_id= ? OR user_id IS ?', @user.id, nil)
	end


# ----------
	private

	def modify_user
		@user = User.find(params[:id])
	end

	def user_params
		params.require(:user).permit(:username,:role,:email,:password,:password_confirmation)
	end

	def checkpoint_params
		params.permit(:checkpoint)
	end

end

app/helpers/users_helper.rb
module UsersHelper
	def role_assigment_limitation(current_user)
    roles = User.roles.keys

    if current_user.Admin?
      roles.delete("Gerente")
      roles.delete("Admin")
    end
    roles
  end

  def resource_name
    :user
  end

  def resource
    @resource ||= User.new
  end

  def devise_mapping
    @devise_mapping ||= Devise.mappings[:user]
  end
end

app/views/users/_form.html.erb
<!-- 
#  id                     :integer          not null, primary key
#  username               :string           default(""), not null
#  role                   :integer
#  created_at             :datetime         not null
#  updated_at             :datetime         not null
#  email                  :string           default(""), not null
#  encrypted_password     :string           default(""), not null
#  reset_password_token   :string
#  reset_password_sent_at :datetime
#  remember_created_at    :datetime
#  sign_in_count          :integer          default(0), not null
#  current_sign_in_at     :datetime
#  last_sign_in_at        :datetime
#  current_sign_in_ip     :inet
#  last_sign_in_ip        :inet
#
 -->
<%= simple_form_for @user do |f| %>
    <br> <br>
  <%= f.error_notification %>
  
  <%= f.input :username, placeholder: 'usuario', label: "Nombre de usuario" %>
  <%= f.input :email, placeholder: 'ejemplo@coonatra.org', label: "Correo lectronico" %>
    <!-- The helper limitation role_assigment_limitation by assignation-->
  <%= f.input :role, default: 1,collection: role_assigment_limitation(@current_user) %>

  <%= f.input :password, placeholder: 'Contraseña',label: "Contraseña" ,:required=> true%>
  <%= f.input :password_confirmation, :label => "confirmación de contraseña",:required=> true, :as => 'password', :input_html => {:name => 'password_confirmation'} %>

  


  <input type="submit" value="Guardar" name="commit" class="pull-right btn-lg btn-primary ">
<% end %>

app/views/users/bus_list.html.erb
<div id="page-wrapper" style="min-height: 650px;">
  <div class="container-fluid">
    <div class="row">
      <div class="col-lg-12">

        <div class="panel-body">
          <div style="display: none;" id="comunication-success" class="alert alert-success alert-dismissable">
            <button type = "button" class = "close" data-dismiss = "alert" aria-hidden = "true">
              &times;
            </button>
            Se agregaron los carros
          </div>
          <div class="table-responsive">
            <%= form_tag url_for( controller: "buses", action: "bus_assignment"),remote: true, id: "multiple-buses-form" do %>
                <table class="table table-bordered">
                  <thead>
                  <tr>
                    <th>Placa</th>
                    <th>Asignar Autobus</th>
                  </tr>
                  </thead>
                  <tbody>
                  <% if !@buses.blank? %>
                      <% @buses.each do |bus|  %>
                          <tr>
                            <td>
                              <%= bus.plate_license %>
                            </td>
                            <td>
                              <%= hidden_field_tag "buses[]", bus.id  %>
                              <%= check_box_tag("buses_assignment", value = ( bus.user_id ? bus.id : "") , checked = bus.user_id ? true : false, class: "subscription", id:  bus.id) %>
                            </td>
                          </tr>
                      <% end %>
                  <% end %>
                  </tbody>
                </table>
                <%= hidden_field_tag 'user_id', @user.id %>
                <%= submit_tag "Guardar", class:"btn btn-success pull-right",id: "multiple-buses-assignment" %>
            <% end %>
          </div>
        </div>

      </div>
      <!-- /.col-lg-12 -->
    </div>
    <!-- /.row -->
  </div>
  <!-- /.container-fluid -->
</div>
<script type="text/javascript" link="multiBuses.js"></script>

app/views/users/checkpoint.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-4 col-md-offset-4">
      <div class="login-panel panel panel-default">
        <div class="panel-heading">
        <h3 class="panel-title">Checkpoint</h3>
        </div>
        <div class="panel-body">
          <%= form_tag(user_checkpoint_path, class:"checkpoint") do |f| %>
            <fieldset>
              <div class="form-group row">
                <label class="col-xs-6" for="checkpoint_control"><h2>Control :</h2></label>
                <div class="col-xs-6">
                  <%= radio_button_tag :checkpoint,"control",true %>
                </div>
                <!-- class: "form-control" -->
              </div>
              <hr>
              <div class="form-group row">
                <label class="col-xs-6" for="checkpoint_terminal"><h2>Terminal :</h2></label>
                <div class="col-xs-6">
                  <%= radio_button_tag :checkpoint, "terminal" %>
                </div>
                <!-- class: "form-control" -->
              </div>
              <%= submit_tag "Escojer un lugar", class: "btn btn-lg btn-success btn-block" %>
            </fieldset>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/users/dashboard.html.erb
<div id="page-wrapper" style="min-height: 650px;">
  <div class="container-fluid dashboard">
    <div class="row">
      <div class="col-lg-12">
      <div class="row"></div>
      <h1> Administración Coonatra </h1>
      </div>
      <!-- /.col-lg-12 -->
    </div>
    <!-- /.row -->
  </div>
  <!-- /.container-fluid -->
</div>

app/views/users/destroy.js.erb
$("#user_id_<%= @user.id %>").hide();

app/views/users/edit.js.erb
$("#content").html(
  '<%= j render "users/form"  %>'
);

app/views/users/index.html.erb
<h4>COONATRA - <i>COOPERATIVA NACIONAL DE TRANSPORTADORES</i></h4>
<%= render partial: 'devise/sessions/new' %>

app/views/users/list_users.html.erb
<div id="page-wrapper" style="min-height: 650px;">
  <div class="container-fluid autobuses">
    <div class="row">
      <div class="col-lg-12">
        <h1 class="page-header"> <%= link_to "Usuarios", usuarios_path %>
          <% if current_user.Gerente? || current_user.Admin? %>
          <%= link_to new_user_path, class: "btn-lg btn-default" do %>
          <i class="fa fa-user-plus fa-fw"></i> Crear
          <% end  %>
          <% end  %>
        </h1>
        <%= flash_import(flash) %>
      </div>
      <!-- /.col-lg-12 -->
    </div>
    <!-- /.row -->
    <div class="row search">
      <div class="col-lg-12">

      </div>
      <!-- /.col-lg-12 -->
    </div>
    <!-- /.row -->
    <div class="row">
      <div id="content" class="col-lg-12">
        <% if !@users.empty? %>
          <ul class="list-group">
            <% @users.each do |user| %>
              <li class="list-group-item" id="user_id_<%= user.id %>">
                <div class="row">
                  <div class="col-xs-6">
                    Usuario: <strong><%= user.username %></strong> <i>(<%= user.role %>)</i>
                  </div>
                  <div class="col-xs-6">

                    <span class="badge">
                      <%= link_to user_path(user), remote: true, method: :delete, data: { confirm: 'Esta seguro de eliminar?' }, class: "btn btn-default btn-xs" do %>
                        <span class="glyphicon glyphicon-trash" aria-hidden="true">eliminar</span>
                      <% end %>
                    </span>
                    <span class="badge">
                      <%= link_to edit_user_path(user), remote: true , class: "btn btn-default btn-xs" do %>
                        <span class="glyphicon glyphicon-pencil" aria-hidden="true">editar</span>
                      <% end %>
                    </span>
                    <% if user.Lector? %>
                      <span class="badge">
                        <%= link_to bus_list_users_path(user) , class: "btn btn-default btn-xs" do %>
                          <span class="glyphicon glyphicon-plus" aria-hidden="true"> Agregar buses</span>
                        <% end %>
                      </span>
                    <% end %>
                  </div>
                </div>
              </li>
            <% end %>
          </ul>
        <% end %>
      </div>
      <!-- /.col-lg-12 -->
    </div>
    <!-- /.row -->
  </div>
  <!-- /.container-fluid -->
</div>

app/views/users/new.html.erb
<div id="page-wrapper" style="min-height: 650px;">
    <div class="container-fluid">
        <div class="row">
            <div class="col-lg-12">
              <%= flash_import(flash) %>
              <%= render "users/form" %>

            </div>
            <!-- /.col-lg-12 -->
        </div>
        <!-- /.row -->
    </div>
    <!-- /.container-fluid -->
</div>