config/routes.rb
Rails.application.routes.draw do
  # resources :users
  
  devise_for :users, skip: [:registrations]
  root 'users#index'
  
  authenticate :user do
    resources :records, except: [:index]
    get 'datos-de-registro' => 'records#search' ,as: :data_list
    post 'traer-records' => 'records#data_list', as: :get_records
    resources :bus_routes do
      collection { post :import }
    end
    get '/programacion' => 'buses#index' ,as: :programacion
    resources :buses, except: [:index] do
      collection { post :import }
    end
    get '/autobuses' => 'buses#list_buses'

  end
  post '/checkpoint' => 'users#checkpoint' ,as: :user_checkpoint
  get '/usuarios' => 'users#list_users'
  scope "/coonatra" do
    resources :users, except: [:index,:show]
    resources :users, only: [] do
      collection do
        get ':id/autobuses' => 'users#bus_list' ,as: :bus_list
        post 'autobuses' => 'buses#bus_assignment' ,as: :bus_assignment
      end
    end

  end
end

app/models/record.rb
# == Schema Information
#
# Table name: records
#
#  id            :integer          not null, primary key
#  register_time :time
#  quantity      :integer
#  register_type :integer
#  user_id       :integer          not null
#  bus_id        :integer          not null
#  created_at    :datetime         not null
#  updated_at    :datetime         not null
#  register_date :date
#

class Record < ActiveRecord::Base
  belongs_to :bus
  validates_presence_of :bus, message: " no registrado"
  validates :quantity, presence: true
  validates :bus_id, presence: true
  enum register_type: [:terminal, :control]
  before_validation :register_type_N_time, :register_type_N_date

  def self.filter_by_bus(bus_id,date)
    records  = where(bus_id: bus_id, register_date: date)
  end

  private

  def register_type_N_time
    if self.register_time == nil
      self.register_time = Time.now.in_time_zone(-5)
    end
  end
  # def register_type_N_date
  #   if self.register_date == nil
  #     self.register_date = Time.now.in_time_zone(-5).to_date
  #   end
  # end
end

app/controllers/records_controller.rb
class RecordsController < ApplicationController
  before_action :role_reader, except: [:data_list, :search]
  before_action :validates_cookies, except: [:data_list,:search]
  before_action :buses_role_verification, only: [:search]
  def search
  end

  def data_list
    @records_external_connection = ExternalConnection.new(
        bus_id: params[:bus_id] ,
        fecha_f: params['initial-date-input'],
        fecha_i: params['initial-date-input'],
        url: ENV['COONATRA_API']
    )
    @passenger_quantity = JSON.parse(@records_external_connection.send_data)
    render "data_list.js.erb"
  end

  def new
  end
  def create
    record = Record.new(record_params)
    record.register_type = cookies[:checkpoint]
    if record.save
      flash[:notice] = "El registro ha sido exitoso"
    else
      flash[:alert] = record.errors.full_messages
    end  
    redirect_to new_record_path 
  end
  private
  def record_params
    params.permit(:quantity,:user_id,:bus_id)
  end 
  def validates_cookies
    if !cookies[:checkpoint]
      redirect_to controller: "users", action: "index"
    end
  end
end

app/helpers/records_helper.rb
module RecordsHelper
  def flash_records(flash)
    if !flash.blank?
      alert_type = ""
      color = ""
      if flash[:notice]
        alert_type = flash[:notice]
        color = "success"
      elsif flash[:alert]
        alert_type = flash[:alert].join(".\t")
          .gsub(/Quantity/,'Numeración')
        color = "danger"
      end
      return "<div class=\"alert alert-#{color} col-xs-7\" 
      role=\"alert\">#{alert_type}</div>".html_safe         
    end 
  end
end

app/views/records/_records.html.erb
  <br>
  <div class="panel panel-info">
    <div class="panel-heading">
      <h3 class="panel-title">Totales</h3>
    </div>
    <div class="panel-body">
      <% if @passenger_quantity.empty? %>
          No hay registros
      <% else %>
          <strong>
            <div class="row">
              <div class="col-xs-12 col-md-6"><h3>Pasajeros</h3></div>
              <div class="col-xs-12 col-md-6"> <h4><%= @passenger_quantity["passengerQuantity"] %></h4></div>
            </div>
            <br>
            <div class="row">
              <div class="col-xs-12 col-md-6"><h3>Viajes</h3></div>
              <div class="col-xs-12 col-md-6"> <h4><%= @passenger_quantity["tripRounds"] %></h4></div>
            </div>
            <h3></h3>
          </strong>
      <% end %>
    </div>
  </div>

app/views/records/data_list.js.erb
$("#passenger-info").show().html(
  '<%= j render "records/records" %>'
);

app/views/records/index_table.html.erb
<thead>
  <tr>
    <th>#</th>
    <th>Placa</th>
  </tr>
</thead>
<tbody>
  <tr>
    <% if @buses.empty? %>
      <td> Nº </td>
      <td> No existes buses en la base de Datos </td>
    <% else %>
      <% @buses.map do |bus| %>
        <td><%= bus.id %></td>
        <td>
          <%= link_to "",  data_list_path, remote: true do %>
            <%= bus.license_plate %><i class="fa fa-chevron-right fa-2x"></i>
          <% end %>
        </td>
      <% end %>
    <% end %>
  </tr>
</tbody>

app/views/records/new.html.erb
<div id="page-wrapper" style="min-height: 650px;">
  <div class="container-fluid">
    <div class="row">
      <div class="col-lg-12">
      <div class="row"></div>
        <%= form_tag records_path, class: "horizontal-form" do |f| %>
            <%= hidden_field_tag :user_id, current_user.id %>
            <div class="form-group">
              <div class="col-md-3">
                <h3>Númeración</h3>
              </div>
              <div class="col-md-5 ">
                <!-- The following options are for number-pad for iOS -->
                <%= number_field_tag :quantity,nil, class:"form-control",min: 0, inputmode: "numeric", pattern: "[0-9]*", title: "Non-negative integral number", placeholder:"Número de contador" %>
              </div>
            </div>
            <div class="form-group">
              <div class="col-md-3">
                <h3>ID AutoBús</h3>
              </div>
              <div class="col-md-5">
                <%= number_field_tag :bus_id,nil,class: "form-control", min: 0, inputmode: "numeric", pattern: "[0-9]*", title: "Non-negative integral number", placeholder: "ID del Autobús" %>
              </div>
            </div>
            <div class="form-group">
              <%= flash_records(flash) %>
              <%= submit_tag 'Registro', class: "col-xs-offset-1 col-xs-4 pull-right btn-lg btn-primary" %>

        <% end %>
        </div>
        <!-- /.col-lg-12 -->
      </div>
      <!-- /.row -->
    </div>
    <!-- /.container-fluid -->
  </div>
</div>

app/views/records/search.html.erb
<div id="page-wrapper" style="min-height: 650px;">
  <div class="container-fluid">
    <div class="row">
      <div class="col-lg-12">
        <h1 class="page-header"> <%= link_to "Lista de datos", data_list_path %>
        </h1>
      </div>
      <!-- /.col-lg-12 -->
    </div>
    <div class="row">
      <div class="col-lg-12">
        <div style="display: none;" id="comunication-error" class="alert alert-danger alert-dismissable">
          <button type = "button" class = "close" data-dismiss = "alert" aria-hidden = "true">
            &times;
          </button>
          Error al consultar datos, intente nuevamente ó comuniquese con administración
        </div>
        <div id="passenger-info"></div>
        <div id="passenger_wrapper">
          <div class="progress" style="display: none;">
            <div class="progress-bar progress-bar-striped active" role="progressbar" aria-valuenow="40" aria-valuemin="0" aria-valuemax="100" style="width:100%">

            </div>
          </div>
        </div>
        <!-- /.records_display -->
        <!-- /.col-lg-12 -->
      </div>
    </div>
    <div id='search-block' class="row">
      <%= form_tag get_records_path, remote: true, id: "passenger-quantity-form" do %>
          <!-- -->
            <div class="col-sm-12">
              <div class="row">
                <div class="col-sm-3">
                  <p>Bus</p> <small>Placa y Código</small>
                </div>
                <div class="col-sm-3"></div>
                <div class="col-sm-6">
                  <div class="select-style">
                    <%= select_tag "bus_license_plate", options_from_collection_for_select(@buses, "plate_license", "plate_license") %>
                  </div>
                  <br>
                  <div class="select-style">
                    <%= select_tag "bus_id", options_from_collection_for_select(@buses, "id", "id") %>
                  </div>
                </div>
              </div>
            </div>
            <div class="col-sm-12">
              <div class="row">
                <div class="col-sm-12">
                  <p>Fecha</p>
                </div>
                <div class="col-sm-9">
                  <div class="form-group btn-block">
                    <div class='input-group date initial-date' id='initial-date'>
                      <input id='initial-date-input' name='initial-date-input' type='text' class="form-control" readonly />
                    <span class="form-control input-group-addon">
                        <span class="glyphicon glyphicon-time"></span>
                    </span>
                    </div>
                  </div>
                </div>
              </div>
            </div>
            <!--div class="col-sm-4">
              <div class="row">
                <div class="col-sm-12">
                  <p>Fecha final</p>
                </div>
                <div class="col-sm-9">
                  <div class="form-group">
                    <div class='input-group date final-date' id='final-date'>
                      <input id='final-date-input' name='final-date-input' type='text' class="form-control" />
                    <span class="input-group-addon">
                        <span class="glyphicon glyphicon-time"></span>
                    </span>
                    </div>
                  </div>
                </div>
              </div>
            </div>
            <br>
            <!-- /.col-lg-12 -->
            <div class="col-sm-12">
              <br>
              <%= submit_tag "Ingresar", class: "btn btn-primary btn-block", id: "passenger-quantity" %>
            </div>
      <% end %>
    </div>
    <!-- form_tag -->

  </div>
</div>
<script type="text/javascript" link="crossButton.js"></script>
<script type="text/javascript" link="records.js"></script>