config/routes.rb
Rails.application.routes.draw do
  # resources :users
  
  devise_for :users, skip: [:registrations]
  root 'users#index'
  
  authenticate :user do
    resources :records, except: [:index]
    get 'datos-de-registro' => 'records#search' ,as: :data_list
    post 'traer-records' => 'records#data_list', as: :get_records
    resources :bus_routes do
      collection { post :import }
    end
    get '/programacion' => 'buses#index' ,as: :programacion
    resources :buses, except: [:index] do
      collection { post :import }
    end
    get '/autobuses' => 'buses#list_buses'

  end
  post '/checkpoint' => 'users#checkpoint' ,as: :user_checkpoint
  get '/usuarios' => 'users#list_users'
  scope "/coonatra" do
    resources :users, except: [:index,:show]
    resources :users, only: [] do
      collection do
        get ':id/autobuses' => 'users#bus_list' ,as: :bus_list
        post 'autobuses' => 'buses#bus_assignment' ,as: :bus_assignment
      end
    end

  end
end

app/controllers/buses_controller.rb
require 'json'
class BusesController < ApplicationController
  before_action :role_editor
  before_action :role_reader
  before_action :buses_role_verification, only: [:index, :list_buses]
  before_action :new_bus, only: [:new]
  before_action :modify_bus, only: [:edit,:destroy]
  before_action :not_admin, only: [:import]

  def index
  end

  def list_buses
  end

  def edit
    render "new.js.erb"
  end

  def bus_assignment
    respond_to do |format|
      format.json {
        buses =  assignment_buses
        Bus.update(buses.keys,buses.values)
        render json: nil, status: :ok
      }
    end
    # flash[:notice] = "Los buses fueron asignados correctmente"
    # redirect_to :back
  end

  def update
    Bus.update(params[:id], bus_params)
    redirect_to action: "list_buses"
  end
  def destroy
    @bus.destroy
    redirect_to action: "list_buses"
  end

  def new
  end

  def create
    @bus = Bus.new(bus_params)

    respond_to do |format|
      if @bus.save
        flash[:notice] = 'El bus fué creado exitosamente'
        format.html {  redirect_to  action: "list_buses" }
        format.json
      else
        flash[:alert] = 'no se ah podido guardar el autobus'
        format.html { redirect_to action: 'list_buses'}
        format.json { render json: @bus.errors, status: :unprocessable_entity }
      end
    end
  end

  def import
    begin
      Bus.add_routes(params[:file])
      flash[:notice] = "Los archivos se han cargado correctamente"
    rescue ArgumentError => e
      flash[:alert] = e.message
    end
    redirect_to action: "index", notice: "Rutas importadas"
  end

  private

  def new_bus
    @bus = Bus.new
  end
  def modify_bus
    @bus = Bus.find(params[:id])
  end
  def bus_params
    params.require(:bus).permit(:id,:plate_license,:driver_name)
  end
  def assignment_buses
    buses = Hash.new
    params['buses_assignment'].each do |bus|
      buses[bus[0].to_s] = {"user_id" => bus[1]["user_id"].to_s == "" ? nil :  bus[1]["user_id"].to_i}
    end
    buses
  end


end

app/helpers/buses_helper.rb
module BusesHelper
  def flash_import(flash)
    if !flash.blank?
      alert_type = ""
      color = ""
      if flash[:notice]
        alert_type = flash[:notice]
        color = "success"
      elsif flash[:alert]
        alert_type = flash[:alert]
        color = "warning"
      end
      return "<div class=\"col-xs-offset-1 col-xs-8 alert alert-#{color}\" role=\"alert\">
              #{alert_type}
            </div>".html_safe 
    end
  end

  def days_in_the_month
    actual_month = l Time.now, format: :short
    html = ""
    (Time.days_in_month(Time.now.to_date.month)).times do |day|  
      day += 1
      html += %Q[
        <th>#{actual_month.capitalize}-#{day}</th>
      ]
    end
    html.html_safe
  end
  def assigned_routes_to(bus)
    days_in_the_month = Time.days_in_month(Time.now.to_date.month)
    d = Date.today
    html = ""
    days_in_the_month.times do |day|
      day += 1
      schedualed_route = bus.operation_dates.where(operation_date: Date.new(d.year,d.month,day)).take
      if schedualed_route
        html += %Q[
          <td> #{schedualed_route.bus_route.name} </td>
        ]
      else
        html += %Q[
          <td> - </td>
        ]
      end
    end
      
    html.html_safe
  end
end

app/views/buses/_form.html.erb
<%= simple_form_for @bus, html:  {id: "bus-form", novalidate: 'novalidate'} do |f| %>
  <%= f.error_notification %>

  <%= f.input :id, label: "Numero" %>

  <%= f.input :plate_license, placeholder: 'AAA 345', label: "Placa" %>


  <input type="submit" value="Enviar" name="commit" class="pull-right btn-lg btn-primary ">
<% end %>

app/views/buses/index.html.erb
<div id="page-wrapper" class="tables" style="min-height: 650px;">
  <div class="container-fluid dashboard">
    <div class="row">
      <div class="col-lg-12">
        <!-- /.col-lg-12 -->
      </div>
      <% if  current_user.Admin? %>
          <div class="row">
            <div class="col-md-12">
              <div class="panel panel-info">
                <div class="panel-heading">
                  <h3 class="panel-title">Archivos de Excel programcación mensual</h3>
                </div>
                <div class="panel-body">
                  <%= form_tag import_buses_path  , multipart: true do %>
                      <div id="file-upload" class="input-group">
              <span class="input-group-btn">
                <span class="btn btn-info btn-file">
                  Buscar:  <%= file_field_tag :file %>
                </span>
              </span>
                        <input type="text" class="form-control" readonly="">
                      </div>

                      <div class="input-group import">
                        <%= submit_tag "Importar", class: "import-xsl btn btn-primary col-xs-3" %>
                        <%=  flash_routes(flash) %>
                      </div><!-- /btn-group -->
                  <% end %>
                </div>
              </div>
            </div>
          </div>
      <% end %>
      <div class="row">
        <div class="col-lg-12">
          <div class="panel panel-default">
            <div class="panel-heading">
              Programación diaria de mes de <%= (l Time.now, format: :short).capitalize  %>
            </div>
            <!-- /.panel-heading -->
            <div class="panel-body">
              <div class="dataTable_wrapper">
                <table class="table table-striped table-bordered table-hover" id="bus-route-table">
                  <thead>
                  <tr>
                    <th>ID</th>
                    <th>Placa</th>
                    <%= days_in_the_month %>
                  </tr>
                  </thead>

                  <tbody>
                  <% @buses.map do |bus| %>
                      <tr>
                        <td><%= bus.id %></td>
                        <td><%= bus.plate_license %></td>
                        <%= assigned_routes_to(bus) %>
                      </tr>
                  <% end %>

                  </tbody>
                </table>
              </div>
              <!-- /.table-responsive -->
              <div class="well">
                <h4>Programación diaria para el mes de <%= (l Time.now, format: :short).capitalize %></h4>
              </div>
            </div>
            <!-- /.panel-body -->
          </div>
          <!-- /.panel -->
        </div>
        <!-- /.col-lg-12 -->
      </div>
      <!-- /.row -->
    </div>
    <!-- /.container-fluid -->
    </div>
  </div>

app/views/buses/list_buses.html.erb
<div id="page-wrapper" style="min-height: 650px;">
  <div class="container-fluid autobuses">
    <div class="row">
      <div class="col-lg-12">
        <h1 class="page-header"> <%= link_to "Autobuses", autobuses_path %>
          <% if current_user.Gerente? || current_user.Admin? %>
              <%= link_to new_bus_path, remote: true, class: "btn-lg btn-default" do %>
                  <i class="fa fa-bus fa-fw"></i> Crear
              <% end  %>
          <% end  %>
        </h1>
        <%= flash_import(flash) %>
      </div>
      <!-- /.col-lg-12 -->
    </div>
    <!-- /.row -->
    <div class="row search">
      <div class="col-lg-12">

      </div>
      <!-- /.col-lg-12 -->
    </div>
    <!-- /.row -->
    <div class="row">
      <div id="content" class="col-lg-12">
        <% if !@buses.empty? %>
            <% @buses.each do |bus| %>
                <ul class="list-group">
                  <li class="list-group-item" id="bus_id_<%= bus.id %>">
                    <div class="btn-group" role="group" aria-label="...">
                      <button type="button" class="btn btn-default btn-xs disabled">
                        Bus de placa <strong><%= bus.plate_license %></strong>
                      </button>
                       <span class="badge">
                          <%= link_to bus_path(bus), method: :delete, data: { confirm: 'Esta seguro de eliminar?' }, class: "btn btn-default btn-xs" do %>
                                 <span class="glyphicon glyphicon-trash" aria-hidden="true">eliminar</span>
                          <% end %>
                       </span>
                        <span class="badge">
                            <%= link_to edit_bus_path(bus), remote: true , class: "btn btn-default btn-xs" do %>
                                <span class="glyphicon glyphicon-pencil" aria-hidden="true">editar</span>
                            <% end %>
                        </span>
                    </div>
                  </li>
                </ul>
            <% end %>
        <% end %>
      </div>
      <!-- /.col-lg-12 -->
    </div>
    <!-- /.row -->
  </div>
  <!-- /.container-fluid -->
</div>

app/views/buses/new.js.erb
$("#content").html(
  "<%= j render 'buses/form' %>"
);
formValidation();