config/routes.rb
Rails.application.routes.draw do
  # resources :users
  
  devise_for :users, skip: [:registrations]
  root 'users#index'
  
  authenticate :user do
    resources :records, except: [:index]
    get 'datos-de-registro' => 'records#search' ,as: :data_list
    post 'traer-records' => 'records#data_list', as: :get_records
    resources :bus_routes do
      collection { post :import }
    end
    get '/programacion' => 'buses#index' ,as: :programacion
    resources :buses, except: [:index] do
      collection { post :import }
    end
    get '/autobuses' => 'buses#list_buses'

  end
  post '/checkpoint' => 'users#checkpoint' ,as: :user_checkpoint
  get '/usuarios' => 'users#list_users'
  scope "/coonatra" do
    resources :users, except: [:index,:show]
    resources :users, only: [] do
      collection do
        get ':id/autobuses' => 'users#bus_list' ,as: :bus_list
        post 'autobuses' => 'buses#bus_assignment' ,as: :bus_assignment
      end
    end

  end
end

app/views/layouts/_header.html.erb
<nav class="navbar navbar-default navbar-static-top" role="navigation" style="margin-bottom: 0">
  <div class="navbar-header">
    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
      <span class="sr-only">Toggle navigation</span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
    </button>
    <!--  <a class="navbar-brand" href="index.html">Administración Coonatra</a>-->
    <%= link_to("Administración Coonatra", root_path, class: "navbar-brand") %>
    <div class="navbar-brand"><%= header_role(current_user.role) %></div>
  </div>
  <!-- /.navbar-header -->
  <ul class="nav navbar-top-links navbar-right">
    <!-- /.dropdown -->

    <li class="dropdown">
      <a class="dropdown-toggle" data-toggle="dropdown" href="#">
        <%= current_user.username %>
        <i class="fa fa-user fa-fw"></i>  <i class="fa fa-caret-down"></i>
      </a>
      <ul class="dropdown-menu dropdown-message">
        <li>
          <%= link_to destroy_user_session_path, :method => :delete do %>
              <i class="fa fa-sign-out fa-fw"></i> Salir
          <% end %>
        </li>
      </ul>
      <!-- /.dropdown-user -->
    </li>
    <!-- /.dropdown -->
  </ul>
  <!-- /.navbar-top-links -->

  <div class="navbar-default sidebar" role="navigation">
    <div class="sidebar-nav navbar-collapse">
      <ul class="nav" id="side-menu">
        <%if current_user.Editor? %>
            <li>
              <%= link_to new_record_path do %>
                  <i class="fa fa-dashboard fa-fw"></i> Editor
              <% end  %>
            </li>
        <% end %>

        <% if  current_user.Gerente? || current_user.Admin? || current_user.Lector?%>
            <li>
              <%= link_to bus_routes_path do %>
                  <i class="fa fa-table fa-fw"></i> Tablas
              <% end  %>
            </li>

            <li>
              <%= link_to programacion_path do %>
                  <i class="fa fa-edit fa-fw"></i> Programación
              <% end  %>
            </li>
            <% if current_user.Gerente? || current_user.Admin?  %>
                <li>
                  <%= link_to autobuses_path do %>
                      <i class="fa fa-wrench fa-fw"></i> AutoBuses
                  <% end  %>
                </li>

                <li>
                  <%= link_to usuarios_path do %>
                      <i class="fa fa-sitemap fa-fw"></i> Usuarios
                  <% end  %>
                </li>
            <% end %>
            <li>
              <%= link_to data_list_path do %>
                  <i class="fa fa-file-text fa-fw"></i> Datos
              <% end  %>
            </li>
        <% end %>
      </ul>
    </div>
    <!-- /.sidebar-collapse -->
  </div>
  <!-- /.navbar-static-side -->
</nav>

app/views/layouts/_page_wrapper.html.erb
<div id="page-wrapper" style="min-height: 650px;">
    <div class="container-fluid">
        <div class="row">
            <div class="col-lg-12">
            
                <h1 class="page-header">Blank</h1>

            </div>
            <!-- /.col-lg-12 -->
        </div>
        <!-- /.row -->
    </div>
    <!-- /.container-fluid -->
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>COONATRA</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
</head>
<body>
  <div id="wrapper">
      <!-- 'navbar' is a helpers-->
      <%= navbar  %>
      <%= yield %>
  </div>
</body>
</html>